### ISSUE TITLE
[Bug]: Buttons styling needs to be done

### ISSUE THREAD

**Issue by Ridhima10** [ChromeGaming/Community-Page#319] opened 2024-06-15 18:32 UTC
### Give a brief about the bug ✍️

Buttons in contribute page are not styled

### What is the expected behavior? 🤔

It should be styled as other buttons

### Provide step by step information to reproduce the bug 📄

![Screenshot 2024-06-16 000206](https://github.com/ChromeGaming/Community-Page/assets/85826117/9750e2b3-f9ba-45ef-8190-1d3788f57811)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Manaregr8** [comment] 2024-06-18 06:01
Hi @Ridhima10 ,

Sorry for the delay caused by my ongoing exams. I had initially assigned it as a level 1 task. If you look at the "Play Games" page, you'll see that the buttons are already styled. You can simply add that same class or copy and paste the code to achieve the same button styles on different pages.

If the problem is complex, I will automatically upgrade it to a level 2 issue after reviewing your work.

Thank you.

**Comment by Manaregr8** [comment] 2024-06-18 10:26
Nicely Done @Ridhima10! keep the work up.

also I can't see leaderboard working, navbar menu button working in smaller screens, and many more can you fix it? 

Thank You, and again great work!

**Closed by Manaregr8** 2024-06-18 10:26 UTC
Labels: gssoc, level2

**Comment by Ridhima10** [comment] 2024-06-19 17:09
@Manaregr8 yes ofc, I can do it. list the tasks need to be done. I'll create issues accordingly and complete it as soon as possible!

**Comment by Manaregr8** [comment] 2024-06-20 06:01
> @Manaregr8 yes ofc, I can do it. list the tasks need to be done. I'll create issues accordingly and complete it as soon as possible!

1. Menu button not working in home page {for smaller screens}. {BUG}
2. Leaderboard not showing up {BUG}
3. Search bar not functioning {BUG}
4. DARK to Light theme switch toggle not working {BUG}
5. In home page the chrome gaming animation is bigger than screen width for smaller screens (it should act like Plag Games Page in smaller screens) {ENHANCEMENT}
6. In about us page the content of about us section is squeezed up in smaller screens (Fix that to have full screen width) {ENHANCEMENT}

This is it for now try raising issues regarding these and will deliver more one's these are done.

**Comment by Ridhima10** [comment] 2024-06-20 12:09
@Manaregr8 I have raised issue for 1,4,5,6

For 2 and 3 i need some clarity
- in 2nd tasks do you want to show a table format in which there will be name and achievement of users or something else. please provide me the data. Then i will raise an issue for this
- in 3rd you want me to fix the Search-bar so it would open and close or you want me to also add the functionality of searchbar to search the items as well?
